name: CD (staging)

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to deploy
        default: AUTO

env:
  TARGET_NAME: hello-bot
  TARGET_STAGE: staging
  TARGET_VERSION: ${{ github.event.inputs.version }}

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install semantic-version setuptools wheel twine
    - name: Resolve target version
      run: echo TARGET_VERSION=$(python scripts/resolve_target_version.py) >> $GITHUB_ENV
    - name: Build package
      run: python setup.py bdist_wheel
    - name: Check package long description
      run: twine check dist/*
    - name: Publish package to TestPyPI
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: twine upload -r testpypi dist/*
